<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuBuilderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $admin_menus = array(
            array(
                "id" => 1,
                "name" => "main_menu",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 2,
                "name" => "footer_menu_one",
                "created_at" => "2025-07-24 12:54:25",
                "updated_at" => "2025-07-24 12:54:25",
            ),
            array(
                "id" => 3,
                "name" => "footer_menu_two",
                "created_at" => "2025-07-24 12:54:44",
                "updated_at" => "2025-07-24 12:54:44",
            ),
            array(
                "id" => 4,
                "name" => "footer_menu_three",
                "created_at" => "2025-07-24 12:55:09",
                "updated_at" => "2025-07-24 12:55:09",
            ),
        );



        $admin_menu_items = array(
            array(
                "id" => 1,
                "label" => "Home",
                "link" => "/",
                "parent_id" => 0,
                "sort" => 0,
                "class" => NULL,
                "menu_id" => 2,
                "depth" => 0,
                "created_at" => "2025-07-24 13:05:41",
                "updated_at" => "2025-07-24 13:06:00",
            ),
            array(
                "id" => 2,
                "label" => "About",
                "link" => "/about",
                "parent_id" => 0,
                "sort" => 1,
                "class" => NULL,
                "menu_id" => 2,
                "depth" => 0,
                "created_at" => "2025-07-24 13:06:25",
                "updated_at" => "2025-07-24 13:06:25",
            ),
            array(
                "id" => 3,
                "label" => "Contact Us",
                "link" => "/contact",
                "parent_id" => 0,
                "sort" => 2,
                "class" => NULL,
                "menu_id" => 2,
                "depth" => 0,
                "created_at" => "2025-07-24 13:07:30",
                "updated_at" => "2025-07-24 13:07:59",
            ),
            array(
                "id" => 4,
                "label" => "Our Service",
                "link" => "#",
                "parent_id" => 0,
                "sort" => 3,
                "class" => NULL,
                "menu_id" => 2,
                "depth" => 0,
                "created_at" => "2025-07-24 13:08:47",
                "updated_at" => "2025-07-24 13:08:47",
            ),
            array(
                "id" => 5,
                "label" => "More About Us",
                "link" => "#",
                "parent_id" => 0,
                "sort" => 4,
                "class" => NULL,
                "menu_id" => 2,
                "depth" => 0,
                "created_at" => "2025-07-24 13:09:25",
                "updated_at" => "2025-07-24 13:09:25",
            ),
            array(
                "id" => 6,
                "label" => "Terms And Condition",
                "link" => "/terms-and-condition",
                "parent_id" => 0,
                "sort" => 3,
                "class" => NULL,
                "menu_id" => 3,
                "depth" => 0,
                "created_at" => "2025-07-24 13:23:20",
                "updated_at" => "2025-07-24 13:34:04",
            ),
            array(
                "id" => 7,
                "label" => "Privacy Policy",
                "link" => "/privacy-policy",
                "parent_id" => 0,
                "sort" => 2,
                "class" => NULL,
                "menu_id" => 3,
                "depth" => 0,
                "created_at" => "2025-07-24 13:30:42",
                "updated_at" => "2025-07-24 13:34:04",
            ),
            array(
                "id" => 8,
                "label" => "Blogs",
                "link" => "/blogs",
                "parent_id" => 0,
                "sort" => 0,
                "class" => NULL,
                "menu_id" => 3,
                "depth" => 0,
                "created_at" => "2025-07-24 13:32:52",
                "updated_at" => "2025-07-24 13:33:46",
            ),
            array(
                "id" => 9,
                "label" => "Chefs",
                "link" => "/chefs",
                "parent_id" => 0,
                "sort" => 1,
                "class" => NULL,
                "menu_id" => 3,
                "depth" => 0,
                "created_at" => "2025-07-24 13:33:34",
                "updated_at" => "2025-07-24 13:34:04",
            ),
            array(
                "id" => 10,
                "label" => "FaQs",
                "link" => "#",
                "parent_id" => 0,
                "sort" => 1,
                "class" => NULL,
                "menu_id" => 4,
                "depth" => 0,
                "created_at" => "2025-07-24 13:38:35",
                "updated_at" => "2025-07-25 12:13:16",
            ),
            array(
                "id" => 11,
                "label" => "Contact",
                "link" => "/contact",
                "parent_id" => 0,
                "sort" => 0,
                "class" => NULL,
                "menu_id" => 4,
                "depth" => 0,
                "created_at" => "2025-07-24 13:44:33",
                "updated_at" => "2025-07-25 12:13:16",
            ),
            array(
                "id" => 12,
                "label" => "About",
                "link" => "/about",
                "parent_id" => 0,
                "sort" => 2,
                "class" => NULL,
                "menu_id" => 4,
                "depth" => 0,
                "created_at" => "2025-07-24 13:44:48",
                "updated_at" => "2025-07-24 13:44:59",
            ),
            array(
                "id" => 13,
                "label" => "Blogs",
                "link" => "/blogs",
                "parent_id" => 0,
                "sort" => 3,
                "class" => NULL,
                "menu_id" => 4,
                "depth" => 0,
                "created_at" => "2025-07-24 13:44:59",
                "updated_at" => "2025-07-24 13:44:59",
            ),
            array(
                "id" => 15,
                "label" => "Chefs",
                "link" => "/chefs",
                "parent_id" => 21,
                "sort" => 5,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 1,
                "created_at" => "2025-07-24 14:32:10",
                "updated_at" => "2025-07-29 11:45:05",
            ),
            array(
                "id" => 16,
                "label" => "Blogs",
                "link" => "/blogs",
                "parent_id" => 0,
                "sort" => 2,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2025-07-24 14:32:30",
                "updated_at" => "2025-07-29 11:45:05",
            ),
            array(
                "id" => 17,
                "label" => "Contact",
                "link" => "/contact",
                "parent_id" => 0,
                "sort" => 3,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2025-07-24 14:32:42",
                "updated_at" => "2025-07-29 11:45:05",
            ),
            array(
                "id" => 18,
                "label" => "Testimonials",
                "link" => "/testimonials",
                "parent_id" => 21,
                "sort" => 6,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 1,
                "created_at" => "2025-07-24 14:33:25",
                "updated_at" => "2025-07-29 11:45:06",
            ),
            array(
                "id" => 19,
                "label" => "Privacy Policy",
                "link" => "/privacy-policy",
                "parent_id" => 21,
                "sort" => 7,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 1,
                "created_at" => "2025-07-24 14:34:05",
                "updated_at" => "2025-07-29 11:45:06",
            ),
            array(
                "id" => 20,
                "label" => "Terms and Conditions",
                "link" => "/terms-and-condition",
                "parent_id" => 21,
                "sort" => 8,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 1,
                "created_at" => "2025-07-24 14:34:37",
                "updated_at" => "2025-07-29 11:45:06",
            ),
            array(
                "id" => 21,
                "label" => "Pages",
                "link" => "#",
                "parent_id" => 0,
                "sort" => 4,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2025-07-24 14:36:13",
                "updated_at" => "2025-07-29 11:45:05",
            ),
            array(
                "id" => 22,
                "label" => "About",
                "link" => "/about",
                "parent_id" => 0,
                "sort" => 1,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2025-07-25 11:57:36",
                "updated_at" => "2025-07-29 11:45:05",
            ),
            array(
                "id" => 26,
                "label" => "Products",
                "link" => "/products",
                "parent_id" => 0,
                "sort" => 0,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2025-07-29 11:44:58",
                "updated_at" => "2025-07-29 11:45:05",
            ),
        );


        DB::table('admin_menus')->insert($admin_menus);
        DB::table('admin_menu_items')->insert($admin_menu_items);
    }
}
